input.onButtonPressed(Button.A, function () {
    basic.showIcon(IconNames.Heart)
    basic.pause(100)
    basic.showString("mama icin tesekkurler!Simdi yine uyku zamani!!!")
    basic.showIcon(IconNames.Asleep)
    soundExpression.yawn.playUntilDone()
})
input.onGesture(Gesture.Shake, function () {
    basic.showIcon(IconNames.Sad)
    basic.showString("Neden beni uyandirdin?!?!")
    soundExpression.sad.playUntilDone()
    basic.showIcon(IconNames.Asleep)
    soundExpression.yawn.playUntilDone()
})
input.onLogoEvent(TouchButtonEvent.Touched, function () {
    soundExpression.yawn.playUntilDone()
    basic.showIcon(IconNames.Happy)
    basic.showString("gunaydin.Mama istiyom!mama nerde?!")
    basic.showIcon(IconNames.Sad)
    basic.showIcon(IconNames.Heart)
    basic.showIcon(IconNames.Happy)
    basic.showString("mama icin tesekkurler!Simdi yine uyku zamani!!!")
    basic.showIcon(IconNames.Asleep)
})
input.onLogoEvent(TouchButtonEvent.Pressed, function () {
    basic.showIcon(IconNames.Happy)
    soundExpression.giggle.playUntilDone()
    basic.showIcon(IconNames.Asleep)
    soundExpression.yawn.playUntilDone()
})
basic.showIcon(IconNames.Asleep)
soundExpression.yawn.playUntilDone()
basic.showIcon(IconNames.Asleep)
